### ISSUE TITLE
Use specific versions of all dependencies

### ISSUE THREAD

**Issue by akoehn** [dialogos-project/dialogos-distribution#1]
Currently, the newest version of every dependency (dialogos & plugins) is used.  This leads to non-reproducibility.

I would like to refer to fixed versions (or tags) in the build.gradle.  Ideally, a script would automatically change the names of the dependencies in the install4j XML file based on the version referenced in the build.config.

**Comment by akoehn** [comment]
Done in 4949eef, but we should make releases and reference them once we have stable versions for dialogos and the plugins.

**Comment by timobaumann** [comment]
does it really make sense to make releases of all plugins and of dialogos and of dialogos-distribution? sounds like a lot of releases. what's the advantage over having just a release of dialogos-distribution that points to specific commit IDs?

**Comment by akoehn** [comment]
A release is just a git tag.  I think it is a good idea to tag dialogos and the plugins for a release because otherwise, it will be hard to see which version was used for the release in retrospect.

**Comment by timobaumann** [comment]
@alexanderkoller and I discussed this today: we'll most likely tag the plugins (although commit IDs are just as good for tagging, but tags are more explicit).

However, plugin tags will not necessarily have the same version as the corresponding dialogos tag. It would be weird to ask of a "new" plugin (e.g. for ROS integration) to start with a version 2.0.3 rather than 1.0.0.

We will make sure that dialogos and dialogos-distribution revisions are always in synchrony for any given release. If you want to find the plugin revision that was distributed alongside dialogos, go check the dependency in dialogos-distribution's build.gradle.
